---

antora:
  name: modules
  dir: www
  modules:
    - name: index
      label: Add the Ansible repository.
    - name: module-02
      label: Inspecting a pre-made example and applying it.
    - name: module-03
      label: Verify the system roles and configurations were applied.
    - name: module-04
      label: Adding a new role and settings
    - name: module-05
      label: Update an existing setting
tabs:
  - name: terminal
    port: 443
    path: /tty
