= Verify the system roles and configurations were applied.

Now that the playbook has been applied to the system, verify that the
updated settings have been applied. Below you will see we use
swappiness, but you could look at any of the included parameters.

.Command
[source,bash,subs="+macros,+attributes",role=execute]
----
cat /proc/sys/vm/swappiness
----

The result should be the following.

.Output
[source,text]
----
20
----


As expected, the setting is now 20 instead of what it started as in the
beginning of the lab.

To verify that session recording is now working, ssh to the system as
the rhel user.

.Command
[source,bash,subs="+macros,+attributes",role=execute]
----
ssh -o "StrictHostKeyChecking no" rhel@rhel
----

Here’s the output.

.Output
[source,text]
----
# ssh -o "StrictHostKeyChecking no" rhel@rhel
Warning: Permanently added 'localhost' (ED25519) to the list of known hosts.
Locale charset is ANSI_X3.4-1968 (ASCII)
Assuming locale environment is lost and charset is UTF-8

ATTENTION! Your session is being recorded!

[rhel@rhel ~]$
----

To complete this section enter the following.

.Command
[source,bash,subs="+macros,+attributes",role=execute]
----
exit
----

You should have seen dialog similar to the output shown above. Success!
the system is now recording terminal sessions for users connecting to
it.

For `client1`, repeat the following command.

.Command
[source,bash,subs="+macros,+attributes",role=execute]
----
ssh -o "StrictHostKeyChecking no" client1
----


.Output
[source,text]
----
root@rhel:~# ssh -o "StrictHostKeyChecking no" rhel@client1
<<< OUTPUT ABRIDGED >>>
ATTENTION! Your session is being recorded!
----


Exit and continue to the next challenge.

.Command
[source,bash,subs="+macros,+attributes",role=execute]
----
exit
----
