= Inspecting a pre-made example and applying it.

To get started, an already created playbook has been created that uses
both the kernel-settings and session recording system roles. You can
inspect the contents of this lab provided playbook to get some more
information about what it will do on your system.

.Command
[source,bash,subs="+macros,+attributes",role=execute]
----
cat soe.yml
----

The output should look like this.

.Output
[source,text]
----
---
- hosts: localhost
  vars:
    kernel_settings_sysctl:
      - name: vm.swappiness
        value: 20
      - name: vm.dirty_ratio
        value: 40
      - name: vm.dirty_expire_centisecs
        value: 500
      - name: vm.dirty_writeback_centisecs
        value: 100
      - name: kernel.sem
        value: "250 32000 100 128"
    tlog_scope_sssd: all
  roles:
    - role: rhel-system-roles.kernel_settings
    - role: rhel-system-roles.tlog
----

From the above output, this playbook will only affect `localhost`. Also,
at the bottom, you will notice the roles included, `kernel_settings` and
`tlog` (session recording) in the playbook. Because these are the only
roles included in the playbook, the `vars` section has variables that
are used by these roles.

The `vars` under the kernel_settings_sysctl section are the values of
parameters to set on the system to change kernel tunables in the
/proc/sys directory structure. The tlog_scope_sssd setting will enable
session recording for all users on the system.

Before you run the playbook and adjust the settings of the system,
verify the current setting for one of the playbook affected values
`vm.swappiness`.

.Command
[source,bash,subs="+macros,+attributes",role=execute]
----
cat /proc/sys/vm/swappiness
----

The output should be

.Output
[source,text]
----
30
----


After you run the playbook, the swappiness value should be updated to be
20.

____
NOTE: swappiness is a setting that determines the kernel’s preference
for using swap space on the system, the value is between 0-100. The
smaller the value, the less preference the kernel has for utilizing swap
space.
____

Let’s apply these roles to `localhost` and `client1`. We need to create
a `hosts.ini` file specifying the hostname `client1`. This host will be
part of the `clients` group. For localhost, we’ll specify that ansible
should execute the playbook locally.

.Command
[source,bash,subs="+macros,+attributes",role=execute]
----
cat > hosts.ini << EOF
localhost  ansible_connection=local
[clients]
client1
EOF
----

.Command
[source,bash,subs="+macros,+attributes",role=execute]
----
cat hosts.ini
----

The `hosts.ini` should contain the following.

.Output
[source,text]
----
[clients]
client1
----

Edit the `soe.yml` playbook to add the `clients` host group. This tells
ansible to apply the system roles in `soe.yml` to `localhost` and
`client1`.

.Command
[source,bash,subs="+macros,+attributes",role=execute]
----
sed -i '/^- hosts: localhost/ s/$/, clients/' soe.yml
----

Check the soe.yml file.

.Command
[source,bash,subs="+macros,+attributes",role=execute]
----
cat soe.yml
----

.Output
[source,text]
----
---
- hosts: localhost, clients
  vars:
    kernel_settings_sysctl:
      - name: vm.swappiness
        value: 20
      - name: vm.dirty_ratio
        value: 40
      - name: vm.dirty_expire_centisecs
        value: 500
      - name: vm.dirty_writeback_centisecs
        value: 100
      - name: kernel.sem
        value: "250 32000 100 128"
    tlog_scope_sssd: all
  roles:
    - role: rhel-system-roles.kernel_settings
    - role: rhel-system-roles.tlog
----


Now run the playbook again to apply the system roles to the clients
group.

.Command
[source,bash,subs="+macros,+attributes",role=execute]
----
ansible-playbook soe.yml -i hosts.ini
----
